spring.application.name=order-history-service


# Uruchamiamy na innym porcie
server.port=8081

# Konfiguracja bazy H2 (wymóg 2c i 2d)
spring.datasource.url=jdbc:h2:mem:orderhistorydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Hibernate
spring.jpa.hibernate.ddl-auto=update